version: '3.8'
services:
  api:
    build: ./api
    container_name: backend_service
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules

  myappui:
    build: ./myappui
    container_name: frontend_service
    ports:
      - "3000:3000"
    stdin_open: true
  